import type { Destination } from '../../types'
import { IMG } from './images'

export const destinations: Destination[] = [
  {
    id: 'dst-tajikistan',
    slug: 'tajikistan',
    name: { ru: 'Таджикистан', tj: 'Тоҷикистон', en: 'Tajikistan' },
    country: 'Tajikistan',
    image: IMG.range,
    description: { ru: 'Страна гор, где ледники и виноградники соседствуют на каждом шагу.', tj: 'Кишвари кӯҳҳо.', en: 'Land of mountains.' },
    keywords: ['tajikistan', 'тоҷикистон', 'таджикистан'],
  },
  {
    id: 'dst-pamir',
    slug: 'pamir',
    name: { ru: 'Памир', tj: 'Помир', en: 'Pamir' },
    country: 'Tajikistan',
    image: IMG.fog,
    description: { ru: 'Крыша мира — второй по высоте горный узел планеты.', tj: 'Боми ҷаҳон.', en: 'The roof of the world.' },
    keywords: ['pamir', 'помир', 'памир', 'murgab', 'мурғоб'],
  },
  {
    id: 'dst-fann',
    slug: 'fann-mountains',
    name: { ru: 'Фанские горы', tj: 'Кӯҳҳои Фон', en: 'Fann Mountains' },
    country: 'Tajikistan',
    image: IMG.peak,
    description: { ru: 'Бирюзовые озёра и двухтысячники в 2 часах от Душанбе.', tj: 'Кӯлҳои фирӯза.', en: 'Turquoise alpine lakes.' },
    keywords: ['fann', 'фон', 'фан', 'озера', 'alauddin', 'chimtarga', 'big alo', 'алаудин'],
  },
  {
    id: 'dst-iskanderkul',
    slug: 'iskanderkul',
    name: { ru: 'Искандеркуль', tj: 'Искандаркӯл', en: 'Iskanderkul' },
    country: 'Tajikistan',
    image: IMG.lakeBoat,
    description: { ru: 'Жемчужина Фанских гор на высоте 2195 метров.', tj: 'Марвориди кӯҳҳои Фон.', en: 'The jewel of the Fanns.' },
    keywords: ['iskanderkul', 'искандеркуль', 'искандаркул', 'iskandarkul'],
  },
  {
    id: 'dst-seven-lakes',
    slug: 'seven-lakes',
    name: { ru: 'Семь озёр', tj: 'Ҳафткӯл', en: 'Seven Lakes' },
    country: 'Tajikistan',
    image: IMG.lake,
    description: { ru: 'Каскад из семи бирюзовых озёр в Шахристанском хребте.', tj: 'Ҳафт кӯли фирӯза.', en: 'Seven turquoise lakes cascade.' },
    keywords: ['seven lakes', 'haftkul', 'ҳафткул', 'семь озёр', 'шахристан'],
  },
  {
    id: 'dst-dushanbe',
    slug: 'dushanbe',
    name: { ru: 'Душанбе', tj: 'Душанбе', en: 'Dushanbe' },
    country: 'Tajikistan',
    image: IMG.cityN,
    description: { ru: 'Зелёная столица с широкими бульварами и фонтанами.', tj: 'Пойтахт.', en: 'The green capital.' },
    keywords: ['dushanbe', 'душанбе', 'дюшанбе'],
  },
  {
    id: 'dst-khujand',
    slug: 'khujand',
    name: { ru: 'Худжанд', tj: 'Хуҷанд', en: 'Khujand' },
    country: 'Tajikistan',
    image: IMG.market,
    description: { ru: 'Древний город на берегу Сырдарьи, 2500 лет истории.', tj: 'Шаҳри 2500-сола.', en: 'A 2500-year-old city.' },
    keywords: ['khujand', 'худжанд', 'хуҷанд', 'sughd', 'согд'],
  },
  {
    id: 'dst-samarkand',
    slug: 'samarkand',
    name: { ru: 'Самарканд', tj: 'Самарқанд', en: 'Samarkand' },
    country: 'Uzbekistan',
    image: IMG.temple,
    description: { ru: 'Жемчужина Шёлкового пути — Регистан и Шахи-Зинда.', tj: 'Марвориди Роҳи абрешим.', en: 'The pearl of the Silk Road.' },
    keywords: ['samarkand', 'самарканд', 'самарқанд', 'uzbekistan', 'узбекистан'],
  },
  {
    id: 'dst-turkey',
    slug: 'turkey',
    name: { ru: 'Турция', tj: 'Туркия', en: 'Turkey' },
    country: 'Turkey',
    image: IMG.balloon,
    description: { ru: 'Стамбул, Каппадокия и бирюзовое побережье.', tj: 'Истамбул ва Каппадокия.', en: 'Istanbul, Cappadocia and the coast.' },
    keywords: ['turkey', 'турция', 'туркия', 'istanbul', 'стамбул', 'cappadocia'],
  },
  {
    id: 'dst-china',
    slug: 'china',
    name: { ru: 'Китай', tj: 'Хитой', en: 'China' },
    country: 'China',
    image: IMG.wall,
    description: { ru: 'Шёлковый путь, Кашгар и колорит Синьцзяна.', tj: 'Роҳи абрешим.', en: 'The Silk Road and Kashgar.' },
    keywords: ['china', 'китай', 'хитой', 'kashgar', 'кашгар', 'silk road'],
  },
  {
    id: 'dst-egypt',
    slug: 'egypt',
    name: { ru: 'Египет', tj: 'Миср', en: 'Egypt' },
    country: 'Egypt',
    image: IMG.camels,
    description: { ru: 'Пирамиды, Нил и Красное море.', tj: 'Ҳаромҳо ва Нилу Баҳри Сурх.', en: 'Pyramids, the Nile and the Red Sea.' },
    keywords: ['egypt', 'египет', 'миср', 'cairo', 'каир', 'sharm'],
  },
]