import type { Review } from '../../types'

export const reviews: Review[] = [
  {
    id: 'rev-1',
    tourId: 'tour-fann-15-lakes',
    author: 'Анна К.',
    rating: 5,
    title: 'Лучшие 7 дней в моей жизни',
    text: 'Бирюзовые озёра Фанских гор превзошли все ожидания. Гид Шерали знает каждую тропу и историю. Ночёвки продуманы, еда вкусная. Спасибо, Тур Шохин!',
    approved: true,
    createdAt: '2026-08-02',
  },
  {
    id: 'rev-2',
    tourId: 'tour-fann-15-lakes',
    author: 'David Miller (UK)',
    rating: 5,
    title: 'Absolutely stunning',
    text: 'The turquoise lakes are unreal. Great logistics, safe driving, and the team handled altitude well. Highly recommend.',
    approved: true,
    createdAt: '2026-07-18',
  },
  {
    id: 'rev-3',
    tourId: 'tour-pamir-highway',
    author: 'Собир М.',
    rating: 5,
    title: 'Памир — это другой мир',
    text: 'Перевал Ак-Байтал на рассвете, юрты у Рангкуля, шашлык в Мургабе — я переводил всё это в слова, но лучше просто поехать. Организация на высоте.',
    approved: true,
    createdAt: '2026-09-01',
  },
  {
    id: 'rev-4',
    tourId: 'tour-pamir-highway',
    author: 'Elena & Marco',
    rating: 5,
    title: 'Road trip of a lifetime',
    text: 'From Garm valley to the Bartang gorge — every day brought new landscapes. The Pamiri people welcomed us like family.',
    approved: true,
    createdAt: '2026-08-20',
  },
  {
    id: 'rev-5',
    tourId: 'tour-iskanderkul',
    author: 'Мадина Р.',
    rating: 5,
    title: 'Идеальные выходные',
    text: 'Самое красивое озеро страны. Шашлык на берегу и купание в бирюзовой воде — что может быть лучше после рабочей недели.',
    approved: true,
    createdAt: '2026-07-29',
  },
  {
    id: 'rev-6',
    tourId: 'tour-iskanderkul',
    author: 'Карина А.',
    rating: 4,
    title: 'Красиво, но многолюдно в сезон',
    text: 'Само озеро потрясающее, гиду пять звёзд. В сезон на Искандеркуле много туристов — лучше ехать во вторник-среду.',
    approved: true,
    createdAt: '2026-08-05',
  },
  {
    id: 'rev-7',
    tourId: 'tour-seven-lakes',
    author: 'Тимур Ж.',
    rating: 5,
    title: 'Семь чудес света',
    text: 'Каждое озеро отличается по цвету. Ночевали у гостеприимной семьи в Маргузоре. Спасибо за аккуратную организацию.',
    approved: true,
    createdAt: '2026-07-11',
  },
  {
    id: 'rev-8',
    tourId: 'tour-turkey',
    author: 'Ольга С.',
    rating: 5,
    title: 'Турция мечты',
    text: 'Каппадокия утром с воздуха — это must. Стамбул за 2 дня показали так, будто жили там всю жизнь. Фото вышли нереальные.',
    approved: true,
    createdAt: '2026-09-03',
  },
  {
    id: 'rev-9',
    tourId: 'tour-samarkand',
    author: 'Шахрам Н.',
    rating: 5,
    title: 'Самарканд глазами местного',
    text: 'Мы нашли друг друга в Душанбе, а встретились в Самарканде. Гид Азиз — живая энциклопедия. Плов на дровах — отдельный вид искусства.',
    approved: true,
    createdAt: '2026-08-15',
  },
  {
    id: 'rev-10',
    tourId: 'tour-family-fanns',
    author: 'Семья Исмоиловых',
    rating: 5,
    title: 'Дети в восторге, родители отдохнули',
    text: 'Дети катались на пони, лепили лепёшки и уснули в палатке под звёзды. Организация кемпинга для детей — топ. Вернёмся на следующий год!',
    approved: true,
    createdAt: '2026-08-25',
  },
  {
    id: 'rev-11',
    tourId: 'tour-egypt',
    author: 'Владимир П.',
    rating: 4,
    text: 'Пирамиды и Луксор оправдали ожидания на 100%. На Красном море отель отличный. Минус звезда — ранние подъёмы.',
    approved: true,
    createdAt: '2026-09-02',
  },
  {
    id: 'rev-12',
    tourId: 'tour-dushanbe-hissar',
    author: 'Наталья В.',
    rating: 5,
    title: 'Идеальное знакомство с Душанбе',
    text: 'Гиссарская крепость на закате — магия. Гид рассказал столько, сколько не найти в путеводителях.',
    approved: true,
    createdAt: '2026-08-30',
  },
  {
    id: 'rev-13',
    tourId: 'tour-pamir-highway',
    author: 'James R.',
    rating: 5,
    title: 'The M41 delivers',
    text: 'Rented a space with Tur Shohin for the full Pamir section. Flawless permits, great vehicle, unforgettable bridges over the Bartang.',
    approved: false,
    createdAt: '2026-09-07',
  },
]