import type { Tour } from '../../types'
import { IMG, ORI } from './images'

export const tours: Tour[] = [
  {
    id: 'tour-fann-15-lakes',
    slug: '15-ozer-fanskih-gor',
    title: { ru: '15 озёр Фанских гор', tj: '15 кӯли кӯҳҳои Фон', en: '15 Lakes of the Fann Mountains' },
    shortDescription: {
      ru: 'Легендарный трек по бирюзовым озёрам Фанских гор — Алаудин, Большое Алло, Куликалон.',
      tj: 'Треки афсонавӣ аз кӯлҳои фирӯзаи кӯҳҳои Фон.',
      en: 'The legendary trek across the turquoise lakes of the Fanns.',
    },
    description: {
      ru: 'Фанские горы — это семьсот квадратных километров кристально чистых озёр, альпийских лугов и гранитных вершин. За семь дней мы пройдём самую красивую часть хребтов Гиссарского и Фанских гор: от альплагеря Алаудин через Большое Алло к Куликалону и Мутным озёрам, с ночёвками в уютных кемпингах и приютах. Маршрут разминочный и очень фотогеничный — подходит трекерам с базовой подготовкой.',
      tj: 'Кӯҳҳои Фон 700 километри мураббаи кӯлҳои тоза, алафзори алпӣ ва қуллаҳои гранитӣ мебошанд.',
      en: 'The Fanns are hundreds of square kilometers of pristine lakes, alpine meadows and granite peaks. Over seven days we traverse the most scenic part of the Hissar and Fann ranges, camping by the brightest lakes of Central Asia.',
    },
    images: [ORI.timurLake, ORI.active, ORI.village, ORI.pamirMount, IMG.river],
    destinationIds: ['dst-fann'],
    categoryIds: ['cat-trekking', 'cat-adventure'],
    country: 'Таджикистан',
    city: 'Душанбе',
    region: 'Фанские горы',
    durationDays: 7,
    difficulty: 'moderate',
    rating: 4.9,
    reviewsCount: 128,
    basePrice: 2500,
    discountPercent: 10,
    groupSizeMin: 2,
    groupSizeMax: 12,
    includes: [
      { ru: 'Трансфер Душанбе — Алаудин и обратно', tj: 'Нақлиёт Душанбе — Алаудин', en: 'Transfer Dushanbe — Alauddin and back' },
      { ru: 'Проживание в кемпингах и горных приютах', tj: 'Истиқомат дар кемпингҳо', en: 'Camp and mountain hut stays' },
      { ru: 'Питание на маршруте (завтраки и ужины)', tj: 'Ғизо (нонгоҳ ва шом)', en: 'Meals on route (breakfast & dinner)' },
      { ru: 'Услуги опытного гида-инструктора', tj: 'Хидмати роҳбалад', en: 'Experienced guide' },
      { ru: 'Разрешения на посещение заповедника', tj: 'Иҷозатнома', en: 'Permits' },
      { ru: 'Групповое снаряжение (палатки, горелки)', tj: 'Тахминоти гуруҳӣ', en: 'Group equipment' },
    ],
    excludes: [
      { ru: 'Обеды на маршруте (купить в деревнях)', tj: 'Хӯроки нисфирӯзӣ', en: 'Lunches on route' },
      { ru: 'Личное снаряжение (рюкзак, спальник)', tj: 'Тахминоти шахсӣ', en: 'Personal gear' },
      { ru: 'Страховка', tj: 'Суғурта', en: 'Insurance' },
    ],
    whatToBring: [
      { ru: 'Треккинговые ботинки с разносом', tj: 'Гетрҳои треккингӣ', en: 'Broken-in hiking boots' },
      { ru: 'Рюкзак 40–60 л и спальник', tj: 'Рюкзак ва халтаи хоб', en: '40–60L backpack and sleeping bag' },
      { ru: 'Флиска и дождевик', tj: 'Ҷомаи гарм ва абруказ', en: 'Fleece and rain jacket' },
      { ru: 'Крем от солнца SPF 50', tj: 'Креми офтобӣ', en: 'SPF 50 sunscreen' },
      { ru: 'Фонарик и пауэрбанк', tj: 'Фонарча ва пауэрбанк', en: 'Headlamp and powerbank' },
    ],
    faq: [
      {
        q: { ru: 'Насколько сложен маршрут?', tj: 'Маршрут чӣ қадар душвор аст?', en: 'How hard is the route?' },
        a: { ru: 'Средний уровень. Переходы 4–7 часов в день с набором до 700 м. Нужна базовая физподготовка.', tj: 'Сатҳи миёна.', en: 'Moderate. Hikes of 4–7h with up to 700m elevation gain.' },
      },
      {
        q: { ru: 'Можно ли с детьми?', tj: 'Бо кӯдак мумкин?', en: 'Can kids join?' },
        a: { ru: 'От 14 лет при хорошей форме. Для младших рекомендуем семейный тур.', tj: 'Аз 14-солагӣ.', en: 'From 14 years old with good fitness.' },
      },
    ],
    days: [
      {
        id: 'd1',
        day: 1,
        title: { ru: 'Душанбе → Алаудин', tj: 'Душанбе → Алаудин', en: 'Dushanbe → Alauddin' },
        description: {
          ru: 'Выезд утром. Трансфер 4 часа к альплагерю Алаудин (3200 м), акклиматизация, прогулка к Нижнему озеру, ужин у костра.',
          tj: 'Сафари 4 соат, акклиматизатсия.',
          en: 'Morning transfer to Alauddin base camp (3200m), acclimatization walk to the lower lake.',
        },
      },
      {
        id: 'd2',
        day: 2,
        title: { ru: 'Большое Алло', tj: 'Кӯли Аллои Калон', en: 'Big Allo Lake' },
        description: {
          ru: 'Переход к Большому Алло — самому глубокому озеру Фанских гор (200 м). Обед с видом на Мутные озёра, ночёвка в приюте.',
          tj: 'Гузариш ба Кӯли Аллои Калон.',
          en: 'Trek to the deepest lake of the Fanns, lunch above the Muddy Lakes.',
        },
      },
      {
        id: 'd3',
        day: 3,
        title: { ru: 'Мутные озёра и водопад', tj: 'Кӯлҳои мутта ва шаршара', en: 'Muddy Lakes & waterfall' },
        description: {
          ru: 'Радиальный выход к бирюзовым Мутным озёрам и 20-метровому водопаду. День лёгкий — для привыкания к высоте.',
          tj: 'Рӯзи сабук барои мутобиқат.',
          en: 'Easy radial hike to the turquoise Muddy Lakes and a 20m waterfall.',
        },
      },
      {
        id: 'd4',
        day: 4,
        title: { ru: 'Куликалон', tj: 'Куликалон', en: 'Kulikalon' },
        description: {
          ru: 'Переход через перевал Алаудин-Мутный (3480 м) к Зелёному и Чёрному озёрам Куликалона. Горный цирк — главная фотопоинт дня.',
          tj: 'Гузариш тавассути ағбаи Алаудин-Мутный.',
          en: 'Cross the Alauddin–Muddy pass to the Kuli Kalon circus lakes.',
        },
      },
      {
        id: 'd5',
        day: 5,
        title: { ru: 'Озеро Зиёрат и Душоха', tj: 'Кӯли Зиёрат', en: 'Ziyarat & Dushokha lakes' },
        description: {
          ru: 'Лёгкий день: озёра Зиёрат и Душоха, панорама на пики Бодхона и Чапдара. Купание в тёплой воде.',
          tj: 'Рӯзи сабук назди кӯлҳо.',
          en: 'Easy day around the beautiful lakes with a swim in warm water.',
        },
      },
      {
        id: 'd6',
        day: 6,
        title: { ru: 'Перевал Чапдара', tj: 'Ағбаи Чапдара', en: 'Chapdara Pass' },
        description: {
          ru: 'Ключевой переход через Чапдара (3050 м) с панорамой всей озерной системы. Спуск к Зеравшанской долине.',
          tj: 'Гузариши асосӣ тавассути Чапдара.',
          en: 'Key crossing with a panorama of the entire lake system.',
        },
      },
      {
        id: 'd7',
        day: 7,
        title: { ru: 'Пенджикент → Душанбе', tj: 'Панҷакент → Душанбе', en: 'Panjakent → Dushanbe' },
        description: {
          ru: 'Возвращение через Пенджикент с обедом в национальной чайхане. Вечером — прибытие в Душанбе.',
          tj: 'Бозгашт тавассути Панҷакент.',
          en: 'Return via Panjakent with lunch at a national teahouse.',
        },
      },
    ],
    locations: [
      { id: 'l1', stop: 1, name: { ru: 'Душанбе', tj: 'Душанбе', en: 'Dushanbe' }, lat: 38.5598, lng: 68.787 },
      { id: 'l2', stop: 2, name: { ru: 'Алаудин', tj: 'Алаудин', en: 'Alauddin' }, lat: 39.293, lng: 68.117 },
      { id: 'l3', stop: 3, name: { ru: 'Большое Алло', tj: 'Аллои Калон', en: 'Big Allo' }, lat: 39.266, lng: 68.108 },
      { id: 'l4', stop: 4, name: { ru: 'Куликалон', tj: 'Куликалон', en: 'Kulikalon' }, lat: 39.198, lng: 68.158 },
      { id: 'l5', stop: 5, name: { ru: 'Пенджикент', tj: 'Панҷакент', en: 'Panjakent' }, lat: 39.4957, lng: 67.6174 },
    ],
    extras: [
      { id: 'ex1', name: { ru: 'Аренда трекингового рюкзака', tj: 'Иҷораи рюкзак', en: 'Backpack rental' }, price: 150 },
      { id: 'ex2', name: { ru: 'Обеды на маршруте', tj: 'Нисфирӯзӣ', en: 'Lunches on route' }, price: 420 },
      { id: 'ex3', name: { ru: 'Личный гид (3 персоны+)', tj: 'Роҳбалади шахсӣ', en: 'Private guide' }, price: 900 },
    ],
    startDates: ['2026-09-18', '2026-09-26', '2026-10-05', '2027-05-15', '2027-06-05', '2027-07-10'],
    featured: true,
    createdAt: '2026-01-12',
  },
  {
    id: 'tour-pamir-highway',
    slug: 'pamirskiy-trakt-dushanbe-osh',
    title: { ru: 'Памирский тракт: Душанбе — Ош', tj: 'Роҳи Памир: Душанбе — Ош', en: 'Pamir Highway: Dushanbe to Osh' },
    shortDescription: {
      ru: 'Легендарная трасса M41 через перевал Ак-Байтал, Мургаб и Бартанг. Увидишь «Крышу мира».',
      tj: 'Роҳи афсонавии M41 тавассути ағбаи Ак-Байтал.',
      en: 'The legendary M41 across the Ak-Baital pass, Murghab and the Bartang valley.',
    },
    description: {
      ru: 'Памирский тракт — одна из самых высокогорных дорог планеты и лучшее дорожное путешествие Азии. За 10 дней проедем от зелёного Душанбе через Гиссарский и Дарвазский хребты, Куляб и Хорог, долину Бартанга, вьюжный Мургаб (3600 м) и перевал Ак-Байтал 4655 м — до кыргызского Оша. Ночёвки в гостевых домах и юртах, встречи с памирцами и горой Исмоили Сомони — это путешествие на всю жизнь.',
      tj: 'Роҳи Памир — яке аз баландтарин роҳҳои ҷаҳон.',
      en: 'One of the highest roads on Earth and Asia\'s best road trip — from green Dushanbe over the Ak-Baital pass and the Bartang valley to Osh.',
    },
    images: [ORI.pamirTrakt, ORI.pamirRoof, ORI.pamirTrek, ORI.pamirMount, IMG.yurt],
    destinationIds: ['dst-tajikistan', 'dst-pamir'],
    categoryIds: ['cat-pamir', 'cat-adventure'],
    country: 'Таджикистан → Кыргызстан',
    city: 'Душанбе — Ош',
    region: 'ГБАО / Памир',
    durationDays: 10,
    difficulty: 'hard',
    rating: 4.9,
    reviewsCount: 96,
    basePrice: 12000,
    discountPercent: 5,
    groupSizeMin: 3,
    groupSizeMax: 8,
    includes: [
      { ru: 'Полное сопровождение на 4WD-автомобиле', tj: 'Нақлиёти 4WD', en: '4WD transportation' },
      { ru: 'Проживание в гостевых домах и юртах', tj: 'Истиқомат', en: 'Guesthouses & yurts' },
      { ru: 'Все разрешения на Памир (GBAO permit)', tj: 'Иҷозатномаҳо', en: 'All GBAO permits' },
      { ru: 'Опытный водитель-гид', tj: 'Роҳбалад', en: 'Experienced driver-guide' },
      { ru: 'Завтраки и ужины', tj: 'Нонгоҳ ва шом', en: 'Breakfasts and dinners' },
    ],
    excludes: [
      { ru: 'Обеды (150–200 сомони на человека)', tj: 'Нисфирӯзӣ', en: 'Lunches' },
      { ru: 'Личные расходы', tj: 'Хароҷоти шахсӣ', en: 'Personal expenses' },
      { ru: 'Страховка', tj: 'Суғурта', en: 'Insurance' },
    ],
    whatToBring: [
      { ru: 'Тёплая куртка (ночью +5°C даже летом)', tj: 'Ҷомаи гарм', en: 'Warm jacket' },
      { ru: 'Крем SPF 50 и тёмные очки', tj: 'Крем ва айнак', en: 'Sunscreen & sunglasses' },
      { ru: 'Спальник (для ночёвок в юртах)', tj: 'Халтаи хоб', en: 'Sleeping bag' },
      { ru: 'Засушенные орехи и шоколад', tj: 'Chocolate', en: 'Snacks' },
      { ru: 'Кроссовки и массажёры для ног', tj: 'Krossovki', en: 'Comfortable shoes' },
    ],
    faq: [
      {
        q: { ru: 'Безопасно ли на Памире?', tj: 'Дар Помир бехатар аст?', en: 'Is the Pamir safe?' },
        a: { ru: 'Да. Памир — один из самых гостеприимных регионов мира, местные жители встречают гостей чаем.', tj: 'Бале. Помир бениҳоят меҳмоннавоз аст.', en: 'Yes — one of the most hospitable regions on Earth.' },
      },
      {
        q: { ru: 'Какой уровень высоты?', tj: 'Баландии роҳ?', en: 'What altitudes?' },
        a: { ru: 'Максимум — перевал Ак-Байтал (4655 м). Нужна хорошая переносимость высоты.', tj: 'Ағбаи Ак-Байтал 4655 м.', en: 'Up to 4655m at Ak-Baital pass.' },
      },
    ],
    days: [
      { id: 'p1', day: 1, title: { ru: 'Душанбе → Куляб', tj: 'Душанбе → Кӯлоб', en: 'Dushanbe → Kulob' }, description: { ru: 'Старт на юг, Гиссарский хребет, город Нурек с ГЭС, вечер в Кулябе.', tj: 'Сафари ба ҷануб.', en: 'Start south through the Hissar range to Kulob.' } },
      { id: 'p2', day: 2, title: { ru: 'Дарваз ущелье', tj: 'Ҳафткӯл? Дарвоз', en: 'Darvoza Gorge' }, description: { ru: 'Спуск в самое глубокое ущелье мира — Дарваз. Ночёвка в Калаи Хумбе.', tj: 'Дарвоза-кӯҳи ҷаҳон.', en: 'Into the deepest gorge on Earth, stay in Kalai Khumb.' } },
      { id: 'p3', day: 3, title: { ru: 'Калаи Хумб — Хорог', tj: 'Қалъаи Хумб — Хоруғ', en: 'Kalai Khumb — Khorog' }, description: { ru: 'Панж и ботанический сад Хорога, памирское гостеприимство.', tj: 'Боғи ботаникии Хоруғ.', en: 'The Panj river and Khorog botanical garden.' } },
      { id: 'p4', day: 4, title: { ru: 'Долина Бартанг', tj: 'Водии Бартанг', en: 'Bartang Valley' }, description: { ru: 'Неделя без дорог за один день: серпантины Бартанга, кишлак Барчидев.', tj: 'Роҳҳои Бартанг.', en: 'The wild Bartang valley, village of Barchidev.' } },
      { id: 'p5', day: 5, title: { ru: 'Яшилькуль и Булкункуль', tj: 'Яшилкӯл', en: 'Yashilkul & Bulunkul' }, description: { ru: 'Два озера контрастов: бирюзовый Яшилькуль и замерзающий даже летом Булкункуль.', tj: 'Ду кӯл.', en: 'Contrasting lakes: turquoise Yashilkul and icy Bulunkul.' } },
      { id: 'p6', day: 6, title: { ru: 'Мургаб', tj: 'Мурғоб', en: 'Murghab' }, description: { ru: 'Высочайший город постсоветского пространства (3600 м), рынок и юрты.', tj: 'Шаҳри 3600 метр.', en: 'The highest town of the former USSR at 3600m.' } },
      { id: 'p7', day: 7, title: { ru: 'Ак-Байтал 4655 м', tj: 'Ақ-Байтал', en: 'Ak-Baital 4655m' }, description: { ru: 'Кульминация — перевал 4655 м, Рангкуль и озёра киргизских кочевников.', tj: 'Баландтарин ағба.', en: 'Climax: the 4655m pass and Rangul lakes.' } },
      { id: 'p8', day: 8, title: { ru: 'Сары-Таш', tj: 'Сари-Тош', en: 'Sary-Tash' }, description: { ru: 'Кыргызский Джиригатель и осмотр древних петроглифов.', tj: 'Петроглифҳо.', en: 'Kyrgyz border town and petroglyphs.' } },
      { id: 'p9', day: 9, title: { ru: 'Ош', tj: 'Ош', en: 'Osh' }, description: { ru: 'Второй город Кыргызстана, гора Сулайман-Тоо и огромный базар.', tj: 'Шаҳри Ош.', en: 'Osh, Sulayman Mountain and the huge bazaar.' } },
      { id: 'p10', day: 10, title: { ru: 'Свободный день', tj: 'Рӯзи озод', en: 'Free day' }, description: { ru: 'Свободный день в Оше или перелёт домой.', tj: 'Рӯзи озод ё парвоз.', en: 'Free time or flight home.' } },
    ],
    locations: [
      { id: 'pa1', stop: 1, name: { ru: 'Душанбе', tj: 'Душанбе', en: 'Dushanbe' }, lat: 38.5598, lng: 68.787 },
      { id: 'pa2', stop: 2, name: { ru: 'Калаи Хумб', tj: 'Қалъаи Хумб', en: 'Kalai Khumb' }, lat: 38.4616, lng: 70.7853 },
      { id: 'pa3', stop: 3, name: { ru: 'Хорог', tj: 'Хоруғ', en: 'Khorog' }, lat: 37.4876, lng: 71.5557 },
      { id: 'pa4', stop: 4, name: { ru: 'Бартанг', tj: 'Бартанг', en: 'Bartang' }, lat: 38.416, lng: 72.6 },
      { id: 'pa5', stop: 5, name: { ru: 'Булкункуль', tj: 'Булкункӯл', en: 'Bulunkul' }, lat: 37.757, lng: 72.956 },
      { id: 'pa6', stop: 6, name: { ru: 'Мургаб', tj: 'Мурғоб', en: 'Murghab' }, lat: 38.1691, lng: 73.98 },
      { id: 'pa7', stop: 7, name: { ru: 'Ак-Байтал', tj: 'Ақ-Байтал', en: 'Ak-Baital' }, lat: 38.007, lng: 73.904 },
      { id: 'pa8', stop: 8, name: { ru: 'Ош', tj: 'Ош', en: 'Osh' }, lat: 40.5134, lng: 72.8161 },
    ],
    extras: [
      { id: 'ex1', name: { ru: 'Спальник в аренду', tj: 'Халтаи хоб', en: 'Sleeping bag rental' }, price: 200 },
      { id: 'ex2', name: { ru: 'Обеды на маршруте', tj: 'Нисфирӯзӣ', en: 'Lunches' }, price: 1800 },
      { id: 'ex3', name: { ru: 'Страховка с покрытием высоты 5000+', tj: 'Суғурта', en: 'High-altitude insurance' }, price: 600 },
    ],
    startDates: ['2026-09-15', '2026-10-01'],
    featured: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'tour-dushanbe-hissar',
    slug: 'dushanbe-i-gissarskaya-krepost',
    title: { ru: 'Душанбе и Гиссарская крепость', tj: 'Душанбе ва Қалъаи Ҳисор', en: 'Dushanbe & Hissar Fortress' },
    shortDescription: {
      ru: 'Знакомство со столицей за два дня: проспекты, фонтаны, базар и древняя Гиссарская крепость.',
      tj: 'Шиносоӣ бо пойтахт дар ду рӯз.',
      en: 'Two days in the capital: boulevards, the National Museum and the Hissar fortress.',
    },
    description: {
      ru: 'Небольшой, но насыщенный тур для первого знакомства с Таджикистаном. Прогуляемся по широким проспектам Душанбе, поднимемся к флагштоку, попробуем национальные лепёшки на базаре, а на второй день отправимся в Гиссар — древнюю цитадель с 3000-летней историей, мавзолеями и буддийским храмом.',
      tj: 'Тури кӯтоҳ барои шиносоӣ бо Тоҷикистон.',
      en: 'A compact but rich introduction to Tajikistan, capped by the ancient Hissar citadel.',
    },
    images: [ORI.dushanbe, ORI.ajina, ORI.silkCity, ORI.village, IMG.market],
    destinationIds: ['dst-dushanbe'],
    categoryIds: ['cat-culture', 'cat-international'],
    country: 'Таджикистан',
    city: 'Душанбе / Гиссар',
    region: 'РРП',
    durationDays: 2,
    difficulty: 'easy',
    rating: 4.8,
    reviewsCount: 210,
    basePrice: 800,
    groupSizeMin: 1,
    groupSizeMax: 16,
    includes: [
      { ru: 'Сопровождение гида', tj: 'Роҳбалад', en: 'Guided tour' },
      { ru: 'Трансферы по программе', tj: 'Нақлиёт', en: 'Transfers' },
      { ru: 'Входные билеты в музей и крепость', tj: 'Билетҳо', en: 'Entrance tickets' },
      { ru: 'Обед в национальной чайхане', tj: 'Хӯроки нисфирӯзӣ', en: 'Lunch at a teahouse' },
    ],
    excludes: [
      { ru: 'Проживание в отеле', tj: 'Истиқомат', en: 'Hotel' },
      { ru: 'Ужин', tj: 'Шом', en: 'Dinner' },
      { ru: 'Личные траты', tj: 'Хароҷоти шахсӣ', en: 'Personal expenses' },
    ],
    whatToBring: [
      { ru: 'Удобная обувь', tj: 'Пойафзоли роҳат', en: 'Comfortable shoes' },
      { ru: 'Головной убор и вода', tj: 'Об ва кӯлоҳ', en: 'Hat and water' },
    ],
    faq: [
      {
        q: { ru: 'Можно ли в один день из Ходжента?', tj: 'Аз Хуҷанд дар як рӯз?', en: 'Can I add it to a Khujand trip?' },
        a: { ru: 'Да, но удобнее как отдельный тур или продолжение маршрута.', tj: 'Хуб, аммо беҳтар алоҳида.', en: 'Best as a standalone or extension.' },
      },
    ],
    days: [
      { id: 'h1', day: 1, title: { ru: 'Душанбе с гидом', tj: 'Душанбе', en: 'Dushanbe tour' }, description: { ru: 'Проспект Рудаки, площадь Дусти, флагшток, Национальный музей и летний базар Мехргон.', tj: 'Рӯдакӣ, Осорхонаи миллӣ.', en: 'Rudaki Avenue, Friendship Square, National Museum and the Mehrgon bazaar.' } },
      { id: 'h2', day: 2, title: { ru: 'Гиссарская крепость', tj: 'Қалъаи Ҳисор', en: 'Hissar Fortress' }, description: { ru: 'Цитадель XII века, мавзолеи, медресе и археологический парк. Возвращение в Душанбе вечером.', tj: 'Цитадели асри XII.', en: 'The 12th-century citadel, mausoleums and archaeological park.' } },
    ],
    locations: [
      { id: 'h1', stop: 1, name: { ru: 'Душанбе', tj: 'Душанбе', en: 'Dushanbe' }, lat: 38.5598, lng: 68.787 },
      { id: 'h2', stop: 2, name: { ru: 'Гиссар', tj: 'Ҳисор', en: 'Hissar' }, lat: 38.5256, lng: 68.5556 },
    ],
    extras: [
      { id: 'ex1', name: { ru: 'Вечерний банный комплекс', tj: 'Ҳаммом', en: 'Bathhouse evening' }, price: 120 },
    ],
    startDates: ['2026-09-20', '2026-10-04', '2026-10-18'],
    createdAt: '2026-02-10',
  },
  {
    id: 'tour-iskanderkul',
    slug: 'iskanderkul-i-kaskad-vodopadov',
    title: { ru: 'Искандеркуль и каскад водопадов', tj: 'Искандаркӯл ва шаршараҳо', en: 'Iskanderkul & Waterfall Cascade' },
    shortDescription: {
      ru: 'Классика выходного дня: озеро на 2195 м, водопад «Сорок девушек» и «Слоновьи ноги».',
      tj: 'Кӯли маъруф дар 2195 метр.',
      en: 'The classic weekend escape: the lake at 2195m and the Fann waterfall.',
    },
    description: {
      ru: 'Искандеркуль — легендарное озеро, названное в честь Александра Македонского. За два дня увидим бирюзовую воду, зажатые между скал «Слоновьи ноги» — ведь по легенде слоновья армия Искандера утонула именно здесь, прогуляемся к шумному водопаду Фанагар и устроим шашлык на берегу.',
      tj: 'Кӯли афсонавӣ ба номи Искандари Мақдунӣ.',
      en: 'A legendary lake named after Alexander the Great, with incredible photo spots and a lakeside barbecue.',
    },
    images: [ORI.active, ORI.pamirMount, ORI.timurLake, ORI.village],
    destinationIds: ['dst-iskanderkul', 'dst-fann'],
    categoryIds: ['cat-adventure', 'cat-family'],
    country: 'Таджикистан',
    city: 'Душанбе',
    region: 'Фанские горы',
    durationDays: 2,
    difficulty: 'easy',
    rating: 4.9,
    reviewsCount: 154,
    basePrice: 1200,
    groupSizeMin: 2,
    groupSizeMax: 15,
    includes: [
      { ru: 'Трансфер Душанбе — Искандеркуль', tj: 'Нақлиёт', en: 'Return transfer' },
      { ru: 'Ужин-шашлык на берегу', tj: 'Шӯрбо ва кабоб', en: 'Lakeside barbecue' },
      { ru: 'Гид-сопровождающий', tj: 'Роҳбалад', en: 'Guide' },
      { ru: 'Разрешение на посещение', tj: 'Иҷозатнома', en: 'Permit' },
    ],
    excludes: [
      { ru: 'Проживание (палатка или гостевой дом — по запросу)', tj: 'Истиқомат', en: 'Accommodation' },
      { ru: 'Завтрак', tj: 'Нонгоҳ', en: 'Breakfast' },
    ],
    whatToBring: [
      { ru: 'Купальник и полотенце', tj: 'Майо', en: 'Swimsuit' },
      { ru: 'Тёплая кофта на вечер', tj: 'Ҷомаи гарм', en: 'Warm layer' },
    ],
    faq: [
      {
        q: { ru: 'Можно ли купаться?', tj: 'Оббозӣ мумкин?', en: 'Can we swim?' },
        a: { ru: 'Летом вода прогревается до +18 °C — для смелых. Дети купаются в более тёплых заводях.', tj: 'Дар тобистон мумкин.', en: 'In summer the lake warms to 18°C — for the brave.' },
      },
    ],
    days: [
      { id: 'i1', day: 1, title: { ru: 'Душанбе → Искандеркуль', tj: 'Душанбе → Искандаркӯл', en: 'Dushanbe → Iskanderkul' }, description: { ru: 'Серпантин через перевал Анзоб, панорамы, обед, прогулка к «Слоновьим ногам», шашлык на закате.', tj: 'Серпантини Анзоб.', en: 'Across the Anzob pass, Fann panorama, the "Elephant Legs" and sunset kebab.' } },
      { id: 'i2', day: 2, title: { ru: 'Водопады → Душанбе', tj: 'Шаршараҳо → Душанбе', en: 'Waterfalls → Dushanbe' }, description: { ru: 'Трек к водопаду Фанагар и смотровой Skala, купание в заводях, возвращение.', tj: 'Шаршараи Фанагар.', en: 'Trek to Fanagar waterfall, swim, return.' } },
    ],
    locations: [
      { id: 'i1', stop: 1, name: { ru: 'Душанбе', tj: 'Душанбе', en: 'Dushanbe' }, lat: 38.5598, lng: 68.787 },
      { id: 'i2', stop: 2, name: { ru: 'Искандеркуль', tj: 'Искандаркӯл', en: 'Iskanderkul' }, lat: 39.0778, lng: 68.3853 },
      { id: 'i3', stop: 3, name: { ru: 'Водопад Фанагар', tj: 'Фанагар', en: 'Fanagar falls' }, lat: 39.0616, lng: 68.711 },
    ],
    extras: [],
    startDates: ['2026-09-12', '2026-09-19', '2026-10-03', '2026-10-10', '2027-04-18'],
    createdAt: '2026-01-20',
  },
  {
    id: 'tour-seven-lakes',
    slug: 'sem-ozer-kazrakov',
    title: { ru: 'Семь озёр Хазрати-Шоха', tj: 'Ҳафткӯл', en: 'Seven Lakes' },
    shortDescription: {
      ru: 'Каскад из семи бирюзовых озёр к северу от Пенджикента с треккингом по альпийским лугам.',
      tj: 'Ҳафт кӯли фирӯза.',
      en: 'Seven turquoise lakes in a single mountain gorge.',
    },
    description: {
      ru: 'Ущелье Шинга, что в пятидесяти километрах от Пенджикента, — настоящая жемчужина Северного Таджикистана. Семь озёр разного цвета — от изумрудного до молочно-голубого — лежат друг над другом на высотах от 1700 до 2800 метров. Идём налегке с ночёвками в гостевых домах кишлаков Маргузор и Хазрат-Шох, а на последнем озере устраиваем фотосессию на фоне зеркальной глади.',
      tj: 'Ҳафт кӯл дар як тангӣи кӯҳӣ.',
      en: 'The Shing gorge hides seven lakes stacked in a single ravine — a photographer\'s dream.',
    },
    images: [ORI.timurLake, ORI.active, ORI.village, IMG.river],
    destinationIds: ['dst-seven-lakes'],
    categoryIds: ['cat-trekking', 'cat-adventure'],
    country: 'Таджикистан',
    city: 'Пенджикент',
    region: 'Согдийская область',
    durationDays: 3,
    difficulty: 'moderate',
    rating: 4.9,
    reviewsCount: 88,
    basePrice: 1500,
    groupSizeMin: 2,
    groupSizeMax: 10,
    includes: [
      { ru: 'Трансферы из Пенджикента', tj: 'Нақлиёт', en: 'Transfers from Panjakent' },
      { ru: 'Проживание в гостевых домах', tj: 'Истиқомат', en: 'Guesthouse stays' },
      { ru: 'Питание (2 завтрака, 1 обед, 2 ужина)', tj: 'Ғизо', en: 'Meals' },
      { ru: 'Гид', tj: 'Роҳбалад', en: 'Guide' },
    ],
    excludes: [
      { ru: 'Обед (купить в деревне)', tj: 'Нисфирӯзӣ', en: 'One lunch' },
      { ru: 'Трансфер Душанбе — Пенджикент', tj: 'Нақлиёт', en: 'Dushanbe transfer' },
    ],
    whatToBring: [
      { ru: 'Треккинговые ботинки', tj: 'Пойафзол', en: 'Hiking shoes' },
      { ru: 'Фотоаппарат', tj: 'Камера', en: 'Camera' },
    ],
    faq: [
      {
        q: { ru: 'Это трудный маршрут?', tj: 'Душвор?', en: 'Is it hard?' },
        a: { ru: 'Умеренный: 5–8 км в день, набор до 600 м. Подойдёт новичкам в хорошей форме.', tj: 'Миёна.', en: 'Moderate, daily 5–8km with up to 600m gain.' },
      },
    ],
    days: [
      { id: 's1', day: 1, title: { ru: 'Озёра 1–4', tj: 'Кӯлҳои 1–4', en: 'Lakes 1–4' }, description: { ru: 'От кишлака Падруд до озера Зазон через Маргузор: первый знакомство с каскадом.', tj: 'То кӯли Зазон.', en: 'From Padrud village past Marguzor to lake Zazon.' } },
      { id: 's2', day: 2, title: { ru: 'Озёра 5–7', tj: 'Кӯлҳои 5–7', en: 'Lakes 5–7' }, description: { ru: 'Дологня, Бибиджонат и Хазрат-Шох — верхние озёра и смотровая на всю долину.', tj: 'Кӯлҳои болоӣ.', en: 'The upper lakes and a panorama over the whole gorge.' } },
      { id: 's3', day: 3, title: { ru: 'Спуск и фотосессия', tj: 'Фотосессия', en: 'Descent & photos' }, description: { ru: 'Ленивый спуск, купание в тёплом озере, возвращение в Пенджикент.', tj: 'Бозгашт.', en: 'Leisurely descent, swim and return to Panjakent.' } },
    ],
    locations: [
      { id: 's1', stop: 1, name: { ru: 'Пенджикент', tj: 'Панҷакент', en: 'Panjakent' }, lat: 39.4957, lng: 67.6174 },
      { id: 's2', stop: 2, name: { ru: 'Озёра Хазрат-Шоха', tj: 'Ҳафткӯл', en: 'Seven Lakes' }, lat: 39.298, lng: 67.755 },
    ],
    extras: [],
    startDates: ['2026-09-17', '2026-10-01', '2026-10-15'],
    createdAt: '2026-03-01',
  },
  {
    id: 'tour-khujand-istaravshan',
    slug: 'hudzhand-i-istaravshan',
    title: { ru: 'Худжанд и Истаравшан', tj: 'Хуҷанд ва Истаравшан', en: 'Khujand & Istaravshan' },
    shortDescription: {
      ru: '2500 лет истории Севера: Сырдарья, крепость и величайшая мечеть Истаравшана.',
      tj: '2500 соли таърихи Шимол.',
      en: 'Two and a half millennia of northern history.',
    },
    description: {
      ru: 'Худжанд — древнейший город Таджикистана, стоящий на Сырдарье со времён Александра Македонского. Увидим цитадель, мечеть-мавзолей Шейха Муслихиддина и знаменитый центральный базар «Панчшанбе». Затем поедем в Истаравшан — город гузов и самую красивую мечеть региона, Мугтеппу и ремесленную слободу.',
      tj: 'Шаҳри қадимтарини Тоҷикистон.',
      en: 'The oldest city of Tajikistan plus the jewel-box architecture of Istaravshan.',
    },
    images: [ORI.kokGumbaz, ORI.silkCity, ORI.ajina, IMG.temple],
    destinationIds: ['dst-khujand'],
    categoryIds: ['cat-culture'],
    country: 'Таджикистан',
    city: 'Худжанд / Истаравшан',
    region: 'Согдийская область',
    durationDays: 2,
    difficulty: 'easy',
    rating: 4.8,
    reviewsCount: 76,
    basePrice: 900,
    groupSizeMin: 2,
    groupSizeMax: 12,
    includes: [
      { ru: 'Трансферы внутри тура', tj: 'Нақлиёт', en: 'Transfers' },
      { ru: 'Экскурсии с гидом', tj: 'Экскурсияҳо', en: 'Guided excursions' },
      { ru: 'Входные билеты', tj: 'Билетҳо', en: 'Tickets' },
      { ru: 'Обед у местной семьи', tj: 'Нисфирӯзӣ', en: 'Lunch with a local family' },
    ],
    excludes: [
      { ru: 'Перелёт/поезд до Худжанда', tj: 'Нақлиёт', en: 'Transport to Khujand' },
      { ru: 'Проживание', tj: 'Истиқомат', en: 'Hotel' },
    ],
    whatToBring: [
      { ru: 'Лёгкий головной убор', tj: 'Кӯлоҳ', en: 'Hat' },
      { ru: 'Фотоаппарат', tj: 'Камера', en: 'Camera' },
    ],
    faq: [
      {
        q: { ru: 'Как добраться до Худжанда?', tj: 'Чӣ тавр расидан?', en: 'How to get to Khujand?' },
        a: { ru: 'Рейсы из Душанбе (40 мин) или трансфер 5 часов. Организуем по запросу.', tj: 'Парвоз 40 дақиқа.', en: 'Flights from Dushanbe (40min) or a 5h transfer.' },
      },
    ],
    days: [
      { id: 'k1', day: 1, title: { ru: 'Старый Худжанд', tj: 'Хуҷанди қадим', en: 'Old Khujand' }, description: { ru: 'Цитадель, мавзолей Шейха Муслихиддина, Сырдарья и набережная, базар Панчшанбе.', tj: 'Қалъа ва базар.', en: 'Citadel, Sheikh Muslikhiddin mausoleum and the great bazaar.' } },
      { id: 'k2', day: 2, title: { ru: 'Истаравшан', tj: 'Истаравшан', en: 'Istaravshan' }, description: { ru: 'Городище Мугтеппа, мечеть-медресе Абдулатиф Султана и ремесленные кварталы.', tj: 'Мачит ва ҳунармандон.', en: 'Mugteppa site, the Sultan mosque and craft quarters.' } },
    ],
    locations: [
      { id: 'k1', stop: 1, name: { ru: 'Худжанд', tj: 'Хуҷанд', en: 'Khujand' }, lat: 40.2827, lng: 69.6199 },
      { id: 'k2', stop: 2, name: { ru: 'Истаравшан', tj: 'Истаравшан', en: 'Istaravshan' }, lat: 39.9108, lng: 69.0031 },
    ],
    extras: [],
    startDates: ['2026-09-22', '2026-10-06', '2026-10-20'],
    createdAt: '2026-03-05',
  },
  {
    id: 'tour-samarkand',
    slug: 'samarkand-registan-shahi-zinda',
    title: { ru: 'Самарканд: Регистан и Шахи-Зинда', tj: 'Самарқанд: Регистон ва Шоҳи Зинда', en: 'Samarkand: Registan & Shah-i-Zinda' },
    shortDescription: {
      ru: 'Древности Шёлкового пути: Регистан, Шахи-Зинда, обсерватория Улугбека и настоящий плов.',
      tj: 'Регистон ва Шоҳи Зинда.',
      en: 'Ancients of the Silk Road: Registan, Shah-i-Zinda and Ulugh Beg\'s observatory.',
    },
    description: {
      ru: 'Самарканд — ровесник Рима. За четыре дня погрузимся в город Тамерлана: площадь Регистан с тремя медресе, некрополь Шахи-Зинда с «улицей райских садов», мавзолей Гур-Эмир, обсерватория Улугбека и руины древнего Афросиаба. По пути — мастерская знаменитой самаркандской бумаги, настоящий плов и пригород Джума с деревом-гигантом.',
      tj: 'Шаҳри Темураленг ва Регистон.',
      en: 'Samarkand, the city of Tamerlane: four days of the Silk Road\'s greatest sights.',
    },
    images: [ORI.silkCity, ORI.kokGumbaz, IMG.temple, IMG.sunset],
    destinationIds: ['dst-samarkand'],
    categoryIds: ['cat-culture', 'cat-international'],
    country: 'Узбекистан',
    city: 'Самарканд',
    region: 'Самаркандская область',
    durationDays: 4,
    difficulty: 'easy',
    rating: 4.8,
    reviewsCount: 142,
    basePrice: 3200,
    groupSizeMin: 2,
    groupSizeMax: 14,
    includes: [
      { ru: 'Проживание в бутик-отеле 3★', tj: 'Меҳмонхона', en: 'Boutique 3★ hotel' },
      { ru: 'Завтраки', tj: 'Нонгоҳ', en: 'Breakfasts' },
      { ru: 'Все экскурсии с лицензированным гидом', tj: 'Экскурсияҳо', en: 'Licensed guide' },
      { ru: 'Входные билеты', tj: 'Билетҳо', en: 'Tickets' },
      { ru: 'Мастер-класс по плову', tj: 'Дарси ошпазӣ', en: 'Plov masterclass' },
    ],
    excludes: [
      { ru: 'Международные перелёты и виза', tj: 'Парвоз ва виза', en: 'Flights & visa' },
      { ru: 'Обеды и ужины (от $3)', tj: 'Нисфирӯзӣ ва шом', en: 'Other meals' },
    ],
    whatToBring: [
      { ru: 'Паспорт', tj: 'Шиноснома', en: 'Passport' },
      { ru: 'Лёгкая одежда и головной убор', tj: 'Либоси сабук', en: 'Light clothing' },
    ],
    faq: [
      {
        q: { ru: 'Нужна ли виза?', tj: 'Виза лозим?', en: 'Do I need a visa?' },
        a: { ru: 'Гражданам РФ и многих стран СНГ виза в Узбекистан не нужна до 30 дней.', tj: 'Ба аксари кишварҳо лозим нест.', en: 'No visa for most CIS countries up to 30 days.' },
      },
    ],
    days: [
      { id: 'sa1', day: 1, title: { ru: 'Прибытие, Регистан', tj: 'Регистон', en: 'Arrival & Registan' }, description: { ru: 'Переезд, вечерняя площадь Регистан с подсветкой — один из красивейших кадров Азии.', tj: 'Регистони шабона.', en: 'Transfer and the floodlit Registan at night.' } },
      { id: 'sa2', day: 2, title: { ru: 'Шахи-Зинда и Гур-Эмир', tj: 'Шоҳи Зинда', en: 'Shah-i-Zinda & Gur-e-Amir' }, description: { ru: 'Некрополь с 44 мавзолеями, мавзолей Тамерлана и обсерватория Улугбека.', tj: '44 мақбара.', en: 'The 44-mausoleum necropolis and the Observatory.' } },
      { id: 'sa3', day: 3, title: { ru: 'Афросиаб и бумага', tj: 'Афросиёб', en: 'Afrosiab & paper' }, description: { ru: 'Древнее городище, мастерская шёлковой бумаги и плов площадью в городскую площадь.', tj: 'Қоғази абрешимӣ.', en: 'Afrosiab ruins and the legendary plov.' } },
      { id: 'sa4', day: 4, title: { ru: 'Джума → домой', tj: 'Ҷумъа', en: 'Juma & home' }, description: { ru: 'Дерево-гигант в пригороде Джума, обед у фермера и выезд.', tj: 'Дарахти ҷумъа.', en: 'The giant Juma tree and departure.' } },
    ],
    locations: [
      { id: 'sa1', stop: 1, name: { ru: 'Регистан', tj: 'Регистон', en: 'Registan' }, lat: 39.6542, lng: 66.9756 },
      { id: 'sa2', stop: 2, name: { ru: 'Шахи-Зинда', tj: 'Шоҳи Зинда', en: 'Shah-i-Zinda' }, lat: 39.6628, lng: 66.9903 },
      { id: 'sa3', stop: 3, name: { ru: 'Афросиаб', tj: 'Афросиёб', en: 'Afrosiab' }, lat: 39.6696, lng: 66.9935 },
    ],
    extras: [
      { id: 'ex1', name: { ru: 'Вечернее шоу в медресе', tj: 'Шоу', en: 'Evening show' }, price: 150 },
      { id: 'ex2', name: { ru: 'Фотосъёмка в национальной одежде', tj: 'Фотосессия', en: 'Costume photoshoot' }, price: 400 },
    ],
    startDates: ['2026-09-25', '2026-10-09', '2026-10-23', '2027-04-02'],
    createdAt: '2026-03-10',
  },
  {
    id: 'tour-turkey',
    slug: 'turciya-stambul-kappadokiya',
    title: { ru: 'Турция: Стамбул и Каппадокия', tj: 'Туркия: Истамбул ва Каппадокия', en: 'Turkey: Istanbul & Cappadocia' },
    shortDescription: {
      ru: 'Два мира одной страны: мегаполис на двух континентах и долина воздушных шаров.',
      tj: 'Истамбул ва водии шарҳо.',
      en: 'Two worlds in one country: two continents and balloon valleys.',
    },
    description: {
      ru: 'Идеальное первое знакомство с Турцией: четыре дня в Стамбуле — Айя-София, Голубая мечеть, Гранд-базар и Босфор, — затем перелёт в Каппадокию с её «сказочными дымоходами», подземными городами и полётом на воздушных шарах на рассвете. В конце — три дня на Средиземноморском побережье в Анталье.',
      tj: 'Сафари одамони ҷаҳонбин дар Туркия.',
      en: 'A perfect first taste of Turkey: Istanbul\'s imperial sights, Cappadocia\'s fairy chimneys and the Mediterranean coast.',
    },
    images: [ORI.turkey, IMG.balloon, IMG.istanbul, IMG.beach],
    destinationIds: ['dst-turkey'],
    categoryIds: ['cat-international', 'cat-culture'],
    country: 'Турция',
    city: 'Стамбул / Гёреме / Анталья',
    region: 'Мармара / Каппадокия / Анталья',
    durationDays: 8,
    difficulty: 'easy',
    rating: 4.9,
    reviewsCount: 61,
    basePrice: 14000,
    groupSizeMin: 2,
    groupSizeMax: 10,
    includes: [
      { ru: 'Все перелёты внутри Турции', tj: 'Парвозҳо', en: 'Domestic flights' },
      { ru: 'Отели 4★ с завтраками', tj: 'Меҳмонхона', en: '4★ hotels with breakfast' },
      { ru: 'Экскурсии с лицензированным гидом', tj: 'Экскурсияҳо', en: 'Guided tours' },
      { ru: 'Трансферы', tj: 'Нақлиёт', en: 'Transfers' },
      { ru: 'Круиз по Босфору', tj: 'Круиз', en: 'Bosphorus cruise' },
    ],
    excludes: [
      { ru: 'Перелёт из Душанбе', tj: 'Парвоз', en: 'International flight' },
      { ru: 'Полёт на шарах (190 $ опционально)', tj: 'Шарҳо', en: 'Balloon flight (optional)' },
      { ru: 'Обеды и ужины', tj: 'Ғизо', en: 'Meals' },
    ],
    whatToBring: [
      { ru: 'Паспорт со сроком действия 6+ мес.', tj: 'Шиноснома', en: 'Passport' },
      { ru: 'Удобная обувь', tj: 'Пойафзол', en: 'Walking shoes' },
      { ru: 'Фотоаппарат', tj: 'Камера', en: 'Camera' },
    ],
    faq: [
      {
        q: { ru: 'Когда сезон шаров?', tj: 'Фасли шарҳо?', en: 'Balloon season?' },
        a: { ru: 'Круглый год, кроме зимы: раннее утро, что на рассвете пиком безопасности.', tj: 'Ғайр аз зимистон.', en: 'Year-round except winter, at dawn.' },
      },
    ],
    days: [
      { id: 't1', day: 1, title: { ru: 'Стамбул: византии', tj: 'Истамбул', en: 'Istanbul' }, description: { ru: 'Айя-София, Голубая мечеть, Ипподром и крытый рынок.', tj: 'Айя-София.', en: 'Hagia Sophia, Blue Mosque and the Grand Bazaar.' } },
      { id: 't2', day: 2, title: { ru: 'Босфор', tj: 'Босфор', en: 'Bosphorus' }, description: { ru: 'Круиз между двумя континентами, обед у воды, Чамлыджа.', tj: 'Круиз.', en: 'A cruise between two continents and Camlica hill.' } },
      { id: 't3', day: 3, title: { ru: 'Стамбул → Каппадокия', tj: 'Каппадокия', en: 'To Cappadocia' }, description: { ru: 'Перелёт в Гёреме, прогулка по долине Любви.', tj: 'Гёреме.', en: 'Fly to Goreme, walk Love valley.' } },
      { id: 't4', day: 4, title: { ru: 'Рассвет на шарах', tj: 'Субҳи шарҳо', en: 'Balloons at dawn' }, description: { ru: 'Старт до восхода: полёт над «сказочными дымоходами».', tj: 'Парвоз.', en: 'Optional sunrise balloon flight.' } },
      { id: 't5', day: 5, title: { ru: 'Подземные города', tj: 'Зеризаминӣ', en: 'Underground cities' }, description: { ru: 'Деринкую и открытые музеи Каппадокии.', tj: 'Деринкую.', en: 'Derinkuyu underground city and open-air museums.' } },
      { id: 't6', day: 6, title: { ru: 'Анталья', tj: 'Анталя', en: 'Antalya' }, description: { ru: 'Перелёт на побережье, старый город Калеичи.', tj: 'Қалеичи.', en: 'Fly to the coast, old town Kaleici.' } },
      { id: 't7', day: 7, title: { ru: 'Свободный день', tj: 'Рӯзи озод', en: 'Free day' }, description: { ru: 'Пляжи, водопады Дюден или парфюмный хаммам.', tj: 'Дюден.', en: 'Duden falls, beaches or a hammam.' } },
      { id: 't8', day: 8, title: { ru: 'Возвращение', tj: 'Бозгашт', en: 'Return' }, description: { ru: 'Трансфер в аэропорт, вылет домой.', tj: 'Парвоз.', en: 'Transfer and flight home.' } },
    ],
    locations: [
      { id: 't1', stop: 1, name: { ru: 'Стамбул', tj: 'Истамбул', en: 'Istanbul' }, lat: 41.0082, lng: 28.9784 },
      { id: 't2', stop: 2, name: { ru: 'Гёреме', tj: 'Гёреме', en: 'Goreme' }, lat: 38.6431, lng: 34.8289 },
      { id: 't3', stop: 3, name: { ru: 'Анталья', tj: 'Анталя', en: 'Antalya' }, lat: 36.8969, lng: 30.7133 },
    ],
    extras: [
      { id: 'ex1', name: { ru: 'Полёт на воздушных шарах', tj: 'Шарҳо', en: 'Balloon flight' }, price: 2100 },
      { id: 'ex2', name: { ru: 'Хаммам с массажем', tj: 'Ҳаммом', en: 'Hammam & massage' }, price: 800 },
    ],
    startDates: ['2026-10-02', '2026-10-16', '2027-05-01'],
    isNew: true,
    createdAt: '2026-06-01',
  },
  {
    id: 'tour-china-silk-road',
    slug: 'kitay-kashgar-shelkovyy-put',
    title: { ru: 'Китай: Кашгар и Шёлковый путь', tj: 'Хитой: Қошғар', en: 'China: Kashgar & Silk Road' },
    shortDescription: {
      ru: 'От Кашгарского базара до Великой китайской стены: три тысячи лет торговли, чая и караван-сараев.',
      tj: 'Қошғар ва Роҳи абрешим.',
      en: 'From the Kashgar bazaar to the Great Wall along the ancient Silk Road.',
    },
    description: {
      ru: 'Отправляемся в самое сердце Шёлкового пути. Стартуем в Кашгаре — городе, где сходятся Уйгурия, Таджикистан, Кыргызстан и Памир. Увидим древний Кашгарский Старый город и ремесленный квартал, озеро Каракуль у подножия Музтаг-Аты, затем перелёт в Сиань — столицу 13 империй с Терракотовой армией, и финальный аккорд — Великая китайская стена и Пекин.',
      tj: 'Роҳи абрешим дар Хитой.',
      en: 'The heart of the Silk Road: Kashgar\'s old town, Karakul lake, Xi\'an\'s Terracotta Army and the Great Wall.',
    },
    images: [ORI.china, IMG.wall, ORI.silkCity, IMG.market],
    destinationIds: ['dst-china'],
    categoryIds: ['cat-international', 'cat-culture'],
    country: 'Китай',
    city: 'Кашгар / Сиань / Пекин',
    region: 'Синьцзян, Шэньси, Пекин',
    durationDays: 7,
    difficulty: 'easy',
    rating: 4.7,
    reviewsCount: 33,
    basePrice: 15000,
    groupSizeMin: 4,
    groupSizeMax: 12,
    includes: [
      { ru: 'Все внутренние перелёты и поезда', tj: 'Парвозҳо', en: 'Internal flights & rail' },
      { ru: 'Отели 4★ с завтраками', tj: 'Меҳмонхона', en: '4★ hotels' },
      { ru: 'Русскоговорящий сопровождающий', tj: 'Роҳбалад', en: 'Russian-speaking host' },
      { ru: 'Входные билеты', tj: 'Билетҳо', en: 'Tickets' },
    ],
    excludes: [
      { ru: 'Виза Китая', tj: 'Виза', en: 'China visa' },
      { ru: 'Международные перелёты', tj: 'Парвоз', en: 'International flights' },
      { ru: 'Обеды и ужины', tj: 'Ғизо', en: 'Meals' },
    ],
    whatToBring: [
      { ru: 'Загранпаспорт и копии документов', tj: 'Шиноснома', en: 'Passport & copies' },
      { ru: 'Наличные (юань)', tj: 'Васх', en: 'CNY cash' },
    ],
    faq: [
      {
        q: { ru: 'Внутренние перелёты включены?', tj: 'Парвозҳо дохил?', en: 'Flights included?' },
        a: { ru: 'Да, все перелёты и скоростные поезда между городами — в цене.', tj: 'Ҳа.', en: 'Yes, all internal transport is included.' },
      },
    ],
    days: [
      { id: 'c1', day: 1, title: { ru: 'Кашгар', tj: 'Қошғар', en: 'Kashgar' }, description: { ru: 'Прогулка по Старому городу и вечерний рынок.', tj: 'Шаҳри қадим.', en: 'The old town and its evening market.' } },
      { id: 'c2', day: 2, title: { ru: 'Каракуль', tj: 'Каракӯл', en: 'Karakul lake' }, description: { ru: 'Озеро у подножия Музтаг-Аты (7546 м), ночёвка в юртах.', tj: 'Кӯли Каракӯл.', en: 'The lake under 7546m Kongur-Muztagh.' } },
      { id: 'c3', day: 3, title: { ru: 'Сиань', tj: 'Сиан', en: "Xi'an" }, description: { ru: 'Перелёт в первую столицу Китая, городская стена и Мусульманский квартал.', tj: 'Шаҳри девор.', en: 'Fly to Xi\'an and its city wall.' } },
      { id: 'c4', day: 4, title: { ru: 'Терракотовая армия', tj: 'Армияи терракотӣ', en: 'Terracotta Army' }, description: { ru: 'Гробница Цинь Шихуанди с 8000 статуй.', tj: '8000 муҷассама.', en: 'Qin Shihuangdi\'s 8000 soldiers.' } },
      { id: 'c5', day: 5, title: { ru: 'Пекин', tj: 'Пекин', en: 'Beijing' }, description: { ru: 'Скоростной поезд в столицу, площадь Тяньаньмэнь.', tj: 'Тянанмэн.', en: 'High-speed rail and Tiananmen Square.' } },
      { id: 'c6', day: 6, title: { ru: 'Великая стена', tj: 'Девори бузург', en: 'Great Wall' }, description: { ru: 'Участок Мутяньюй — самый фотогеничный и менее туристический.', tj: 'Мутяню.', en: 'The Mutianyu section, wilder and rarer.' } },
      { id: 'c7', day: 7, title: { ru: 'Вылет', tj: 'Парвоз', en: 'Departure' }, description: { ru: 'Запретный город или свободное время до вылета.', tj: 'Шаҳри манъ.', en: 'Forbidden City or free time.' } },
    ],
    locations: [
      { id: 'c1', stop: 1, name: { ru: 'Кашгар', tj: 'Қошғар', en: 'Kashgar' }, lat: 39.4647, lng: 75.987 },
      { id: 'c2', stop: 2, name: { ru: 'Сиань', tj: 'Сиан', en: "Xi'an" }, lat: 34.3416, lng: 108.9398 },
      { id: 'c3', stop: 3, name: { ru: 'Пекин', tj: 'Пекин', en: 'Beijing' }, lat: 39.9042, lng: 116.4074 },
    ],
    extras: [],
    startDates: ['2026-10-08', '2026-11-05', '2027-04-20'],
    createdAt: '2026-05-20',
  },
  {
    id: 'tour-egypt',
    slug: 'egipet-piramidy-luksor-krasnoe-more',
    title: { ru: 'Египет: пирамиды, Луксор и Красное море', tj: 'Миср: ҳаромҳо, Луксор', en: 'Egypt: Pyramids, Luxor & Red Sea' },
    shortDescription: {
      ru: 'Древний Египет за неделю: Гизу, Луксор, Нил и дайвинг на Красном море.',
      tj: 'Ҳаромҳо ва Баҳри Сурх.',
      en: 'Seven days of pharaohs, the Nile and Red Sea diving.',
    },
    description: {
      ru: 'Классический Египет без «пляжной жвачки»: два дня в Каире с пирамидами Гизы и Египетским музеем, затем Луксор — Карнакский храм, Долина царей и храм Хатшепсут, и финальные три дня на Красном море в Хургаде с возможностью дайвинга или экскурсии на остров.',
      tj: 'Сафари пурра дар Миср.',
      en: 'Seven days of Egypt\'s greatest hits: Giza, the National Museum, Luxor\'s Valley of the Kings and a Red Sea finale.',
    },
    images: [ORI.egypt, IMG.camels, IMG.desert, IMG.beach],
    destinationIds: ['dst-egypt'],
    categoryIds: ['cat-international', 'cat-culture'],
    country: 'Египет',
    city: 'Каир / Луксор / Хургада',
    region: 'Каир, Луксор, Красное море',
    durationDays: 9,
    difficulty: 'easy',
    rating: 4.8,
    reviewsCount: 47,
    basePrice: 13000,
    discountPercent: 10,
    groupSizeMin: 4,
    groupSizeMax: 20,
    includes: [
      { ru: 'Перелёты внутри Египта', tj: 'Парвозҳо', en: 'Domestic flights' },
      { ru: 'Отели 4–5★ с завтраками', tj: 'Меҳмонхона', en: 'Hotels' },
      { ru: 'Экскурсии с гидом', tj: 'Экскурсияҳо', en: 'Sightseeing' },
      { ru: 'Трансферы и входные билеты', tj: 'Билетҳо', en: 'Transfers & tickets' },
    ],
    excludes: [
      { ru: 'Виза (25 $ на границе)', tj: 'Виза', en: 'Visa on arrival' },
      { ru: 'Международные перелёты', tj: 'Парвоз', en: 'International flight' },
      { ru: 'Обеды и ужины', tj: 'Ғизо', en: 'Meals' },
      { ru: 'Полёт над пирамидами (опция)', tj: 'Парвоз', en: 'Nile flight' },
    ],
    whatToBring: [
      { ru: 'Купальник и рифовые тапки', tj: 'Майо', en: 'Swimsuit' },
      { ru: 'Лёгкая одежда из натуральных тканей', tj: 'Либос', en: 'Light cotton clothes' },
    ],
    faq: [
      {
        q: { ru: 'Жарко ли в октябре?', tj: 'Гарм аст?', en: 'Hot in October?' },
        a: { ru: 'Комфортно: днём до +30 °C, вода +26 °C.', tj: 'Комфорт.', en: 'Comfortable: +30°C days, +26°C water.' },
      },
    ],
    days: [
      { id: 'e1', day: 1, title: { ru: 'Каир и Гизу', tj: 'Қоҳира', en: 'Cairo & Giza' }, description: { ru: 'Прилёт, пирамиды Хеопса и Сфинкс на закате.', tj: 'Ҳаромҳо.', en: 'Arrival and dusk at Giza.' } },
      { id: 'e2', day: 2, title: { ru: 'Египетский музей', tj: 'Осорхона', en: 'Museum & Old Cairo' }, description: { ru: 'Сокровища Тутанхамона и Коптский квартал.', tj: 'Тутанхамон.', en: 'Tutankhamun\'s treasures.' } },
      { id: 'e3', day: 3, title: { ru: 'Луксор', tj: 'Луксор', en: 'Luxor' }, description: { ru: 'Перелёт и прогулка по Карнакскому храму.', tj: 'Карнак.', en: 'Fly to Luxor and Karnak.' } },
      { id: 'e4', day: 4, title: { ru: 'Долина царей', tj: 'Водии шоҳон', en: 'Valley of the Kings' }, description: { ru: 'Гробницы фараонов и храм Хатшепсут.', tj: 'Қабрҳо.', en: 'Royal tombs and Hatshepsut\'s temple.' } },
      { id: 'e5', day: 5, title: { ru: 'Хургада', tj: 'Ҳурғада', en: 'Hurghada' }, description: { ru: 'Переезд на Красное море, заселение в отель.', tj: 'Баҳри Сурх.', en: 'Transfer to the Red Sea coast.' } },
      { id: 'e6', day: 6, title: { ru: 'Дайвинг', tj: 'Дайвинг', en: 'Diving day' }, description: { ru: 'Остров Гуфтун и коралловые рифы (опция).', tj: 'Рифҳо.', en: 'Giftun island and coral reefs.' } },
      { id: 'e7', day: 7, title: { ru: 'Свободный день', tj: 'Рӯзи озод', en: 'Free day' }, description: { ru: 'Марина, аквариум или пляж.', tj: 'Пляж.', en: 'Marina, aquarium or beach.' } },
      { id: 'e8', day: 8, title: { ru: 'Свободный день', tj: 'Рӯзи озод', en: 'Free day' }, description: { ru: 'Опционально: круиз на Красном море.', tj: 'Круиз.', en: 'Optional sea cruise.' } },
      { id: 'e9', day: 9, title: { ru: 'Вылет', tj: 'Парвоз', en: 'Departure' }, description: { ru: 'Трансфер в аэропорт Хургады.', tj: 'Аэропорт.', en: 'Transfer to the airport.' } },
    ],
    locations: [
      { id: 'e1', stop: 1, name: { ru: 'Каир', tj: 'Қоҳира', en: 'Cairo' }, lat: 30.0444, lng: 31.2357 },
      { id: 'e2', stop: 2, name: { ru: 'Луксор', tj: 'Луксор', en: 'Luxor' }, lat: 25.6872, lng: 32.6396 },
      { id: 'e3', stop: 3, name: { ru: 'Хургада', tj: 'Ҳурғада', en: 'Hurghada' }, lat: 27.2579, lng: 33.8116 },
    ],
    extras: [
      { id: 'ex1', name: { ru: 'Полёт над пирамидами', tj: 'Парвоз', en: 'Nile flight' }, price: 1500 },
      { id: 'ex2', name: { ru: 'Дайвинг-день (2 погружения)', tj: 'Дайвинг', en: 'Diving day' }, price: 1200 },
    ],
    startDates: ['2026-10-12', '2026-11-09', '2027-02-15'],
    isNew: true,
    createdAt: '2026-07-15',
  },
  {
    id: 'tour-somoni-peak',
    slug: 'voshozhdenie-na-pik-ismoila-somoni',
    title: { ru: 'Восхождение на Пик Исмоила Сомони', tj: 'Баромад ба қуллаи Исмоили Сомонӣ', en: 'Ismoil Somoni Peak Expedition' },
    shortDescription: {
      ru: 'Высочайшая вершина Таджикистана — 7495 м. Экспедиция для опытных альпинистов.',
      tj: 'Қуллаи 7495 метр дар Помир.',
      en: 'The highest summit in Tajikistan at 7495m — a serious expedition.',
    },
    description: {
      ru: 'Пик Исмоила Сомони (бывший пик Коммунизма) — третья по высоте вершина бывшего СССР и центральный объект Памирского оледенения. Экспедиция длится две недели: сплав по реке Муксу, акклиматизационные выходы, штурм с базового лагеря 5200 м через перевал Гармо и восхождение на вершину 7495 м. Проводят два опытных гида, полное высотное и ледовое снаряжение включено.',
      tj: 'Экспедицияи высотои калон дар Помир.',
      en: 'A fortnight expedition to the 7495m summit via the Garmo pass, led by two certified mountain guides.',
    },
    images: [ORI.pamirRoof, ORI.pamirMount, ORI.pamirTrek, IMG.peak],
    destinationIds: ['dst-pamir'],
    categoryIds: ['cat-climbing', 'cat-pamir'],
    country: 'Таджикистан',
    city: 'Душанбе',
    region: 'Памир / хребет Академии Наук',
    durationDays: 14,
    difficulty: 'extreme',
    rating: 4.9,
    reviewsCount: 12,
    basePrice: 28000,
    groupSizeMin: 2,
    groupSizeMax: 6,
    includes: [
      { ru: 'Полное высотное снаряжение', tj: 'Тахминот', en: 'Full high-altitude gear' },
      { ru: 'Питание на маршруте', tj: 'Ғизо', en: 'All expedition food' },
      { ru: 'Два сертифицированных гида', tj: 'Ду роҳбалад', en: 'Two certified guides' },
      { ru: 'Радиосвязь и спутниковый телефон', tj: 'Радио', en: 'Satellite comms' },
      { ru: 'Разрешения и регистрация', tj: 'Иҷозатнома', en: 'Permits' },
    ],
    excludes: [
      { ru: 'Авиаперелёты и страховка с высотой 7000+', tj: 'Парвоз', en: 'Flights & extreme insurance' },
      { ru: 'Баллоны кислорода (по запросу)', tj: 'Кислород', en: 'Oxygen (optional)' },
    ],
    whatToBring: [
      { ru: 'Опыт восхождений выше 6000 м', tj: 'Таҷриба', en: '6000m+ experience' },
      { ru: 'Личные лекарства', tj: 'Дору', en: 'Personal meds' },
    ],
    faq: [
      {
        q: { ru: 'Сегодня летом 2027, есть ли свободные места?', tj: 'Ҷой ҳаст?', en: 'Spaces available?' },
        a: { ru: 'На сезон 2027 набираем группу до 6 человек. Нужна предварительная проверка снаряжения.', tj: 'То 6 нафар.', en: 'We take up to 6 climbers for 2027.' },
      },
    ],
    days: [
      { id: 'so1', day: 1, title: { ru: 'Душанбе', tj: 'Душанбе', en: 'Dushanbe' }, description: { ru: 'Сбор группы, проверка снаряжения, брифинг.', tj: 'Брифинг.', en: 'Gear check and briefing.' } },
      { id: 'so2', day: 2, title: { ru: 'Джиригатель', tj: 'Зиригат', en: 'Jirgital' }, description: { ru: 'Трансфер на юг, ночёвка в Джиргитале.', tj: 'Нақлиёт.', en: 'Drive south to Jirgital.' } },
      { id: 'so3', day: 3, title: { ru: 'Река Муксу', tj: 'Муксу', en: 'Muksu river' }, description: { ru: 'Первый день по оледенению Муксу, установка промежуточного лагеря.', tj: 'Оледенение.', en: 'Into the Muksu glaciation.' } },
      { id: 'so4', day: 4, title: { ru: 'Базовый лагерь 4200 м', tj: 'Лагери 4200', en: 'Base camp 4200m' }, description: { ru: 'Выход в базовый лагерь у подножия Гармо.', tj: 'Лагер.', en: 'Reach base camp at the foot of Garmo.' } },
      { id: 'so5', day: 5, title: { ru: 'Акклиматизация 1', tj: 'Акклиматизатсия', en: 'Acclimatization I' }, description: { ru: 'Восхождение до 4900 м и спуск.', tj: '4900 м.', en: 'Climb to 4900m and descend.' } },
      { id: 'so6', day: 6, title: { ru: 'Акклиматизация 2', tj: 'Акклиматизатсия', en: 'Acclimatization II' }, description: { ru: 'Передовой лагерь 5200 м, ночёвка.', tj: '5200 м.', en: 'Forward camp at 5200m, overnight.' } },
      { id: 'so7', day: 7, title: { ru: 'Перевал Гармо', tj: 'Гармо', en: 'Garmo pass' }, description: { ru: 'Обработка перевала, работа с верёвками.', tj: 'Верёвка.', en: 'Fix ropes on the Garmo pass.' } },
      { id: 'so8', day: 8, title: { ru: 'Лагерь 3', tj: 'Лагери 3', en: 'Camp III' }, description: { ru: 'Подъём с грузом в лагерь 3 на 5800 м.', tj: '5800 м.', en: 'Carry loads to 5800m.' } },
      { id: 'so9', day: 9, title: { ru: 'Отдых', tj: 'Истироҳат', en: 'Rest day' }, description: { ru: 'День отдыха и погодное окно.', tj: 'Истироҳат.', en: 'Rest and weather-window watch.' } },
      { id: 'so10', day: 10, title: { ru: 'Лагерь 4 — 6400 м', tj: '6400 м', en: 'Camp IV 6400m' }, description: { ru: 'Выход в высотный лагерь.', tj: 'Лагер.', en: 'Move to the high camp.' } },
      { id: 'so11', day: 11, title: { ru: 'Штурм 7495 м', tj: 'Қулла 7495', en: 'Summit push' }, description: { ru: 'Ночной старт, вершина на рассвете.', tj: 'Қулла.', en: 'Night start, summit at dawn.' } },
      { id: 'so12', day: 12, title: { ru: 'Спуск', tj: 'Фуруд', en: 'Descent' }, description: { ru: 'Спуск в базовый лагерь.', tj: 'Фуруд.', en: 'Descent to base camp.' } },
      { id: 'so13', day: 13, title: { ru: 'Джиргиталь', tj: 'Зиригат', en: 'Jirgital' }, description: { ru: 'Возвращение в цивилизацию.', tj: 'Бозгашт.', en: 'Return to Jirgital.' } },
      { id: 'so14', day: 14, title: { ru: 'Душанбе, банкет', tj: 'Душанбе', en: 'Dushanbe, celebration' }, description: { ru: 'Прибытие, банкет и сертификаты.', tj: 'Банкет.', en: 'Arrival, celebration dinner and certificates.' } },
    ],
    locations: [
      { id: 'som1', stop: 1, name: { ru: 'Душанбе', tj: 'Душанбе', en: 'Dushanbe' }, lat: 38.5598, lng: 68.787 },
      { id: 'som2', stop: 2, name: { ru: 'Базовый лагерь', tj: 'Лагер', en: 'Base camp' }, lat: 38.92, lng: 72.05 },
      { id: 'som3', stop: 3, name: { ru: 'Пик Сомони 7495 м', tj: 'Қулла 7495', en: 'Summit 7495m' }, lat: 38.9433, lng: 72.0184 },
    ],
    extras: [],
    startDates: ['2027-07-20'],
    createdAt: '2026-03-20',
  },
  {
    id: 'tour-khodja-obigarm',
    slug: 'zimniy-hodja-obigarm',
    title: { ru: 'Зимний Ходжа-Обигарм', tj: 'Зимистони Хоҷа Обигарм', en: 'Winter at Khodja Obi Garm' },
    shortDescription: {
      ru: 'Горячие источники, снег и горный воздух в 90 км от Душанбе.',
      tj: 'Чашмаҳои гарм дар зимистон.',
      en: 'Hot springs, snow and mountain air near Dushanbe.',
    },
    description: {
      ru: 'Ходжа-Обигарм — курорт с радоновыми термальными источниками на высоте 1900 метров. Зимой это идеальное убежище: днём катание на ватрушках и прогулки по снегу, вечером — горячие бассейны под открытым небом и горный чай. Лёгкий трёхдневный тур без напряга, отлично подходит семьям и компаниям друзей.',
      tj: 'Курорти термалӣ дар зимистон.',
      en: 'A three-day winter escape to radon hot springs at 1900m, with sleighing and starry skies.',
    },
    images: [ORI.active, ORI.pamirMount, ORI.village, IMG.hotspring],
    destinationIds: ['dst-dushanbe'],
    categoryIds: ['cat-winter', 'cat-family'],
    country: 'Таджикистан',
    city: 'Ходжа-Обигарм',
    region: 'РРП',
    durationDays: 3,
    difficulty: 'easy',
    rating: 4.8,
    reviewsCount: 64,
    basePrice: 1500,
    groupSizeMin: 2,
    groupSizeMax: 12,
    includes: [
      { ru: 'Трансфер и проживание', tj: 'Нақлиёт', en: 'Transfer & stay' },
      { ru: 'Доступ к термальным бассейнам', tj: 'Бассейн', en: 'Thermal pools' },
      { ru: 'Завтраки и ужины', tj: 'Ғизо', en: 'Meals' },
      { ru: 'Аренда ватрушек', tj: 'Ватрушка', en: 'Sledges' },
    ],
    excludes: [
      { ru: 'Обеды', tj: 'Нисфирӯзӣ', en: 'Lunches' },
      { ru: 'Личный транспорт', tj: 'Авто', en: 'Personal transport' },
    ],
    whatToBring: [
      { ru: 'Купальник', tj: 'Майо', en: 'Swimsuit' },
      { ru: 'Тёплая зимняя одежда', tj: 'Либоси гарм', en: 'Warm clothes' },
    ],
    faq: [
      {
        q: { ru: 'Какая температура воды?', tj: 'Ҳарорати об?', en: 'Water temperature?' },
        a: { ru: '+38…45 °C в бассейнах круглый год.', tj: '+38…45 °C.', en: '38–45°C all year.' },
      },
    ],
    days: [
      { id: 'z1', day: 1, title: { ru: 'Душанбе → Обигарм', tj: 'Обигарм', en: 'To Obi Garm' }, description: { ru: 'Выезд утром, заселение, вечерние бассейны.', tj: 'Бассейн.', en: 'Morning drive, evening pools.' } },
      { id: 'z2', day: 2, title: { ru: 'Снежный день', tj: 'Рӯзи барфӣ', en: 'Snow day' }, description: { ru: 'Ватрушки, снеговая крепость, хаммам.', tj: 'Ватрушка.', en: 'Sledging, snow forts and spa.' } },
      { id: 'z3', day: 3, title: { ru: 'Возвращение', tj: 'Бозгашт', en: 'Return' }, description: { ru: 'Утренние источники, обед, Душанбе.', tj: 'Бозгашт.', en: 'Morning springs and return.' } },
    ],
    locations: [
      { id: 'z1', stop: 1, name: { ru: 'Душанбе', tj: 'Душанбе', en: 'Dushanbe' }, lat: 38.5598, lng: 68.787 },
      { id: 'z2', stop: 2, name: { ru: 'Ходжа-Обигарм', tj: 'Обигарм', en: 'Obi Garm' }, lat: 38.9, lng: 68.55 },
    ],
    extras: [
      { id: 'ex1', name: { ru: 'Массаж', tj: 'Массеж', en: 'Massage' }, price: 150 },
    ],
    startDates: ['2026-12-18', '2026-12-25', '2027-01-02', '2027-01-15'],
    isNew: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'tour-family-fanns',
    slug: 'semeynoe-puteshestvie-fannskie-gory',
    title: { ru: 'Семейный тур: Фанские горы + Душанбе', tj: 'Сафари оилавӣ: Фон + Душанбе', en: 'Family trip: Fanns + Dushanbe' },
    shortDescription: {
      ru: 'Пять дней для всей семьи: лёгкие прогулки, лошади, озеро и город с детьми.',
      tj: 'Панҷ рӯз барои тамоми оила.',
      en: 'Five family-friendly days of gentle hikes, horses, lakes and the city.',
    },
    description: {
      ru: 'Специальный тур для семей с детьми от 5 лет. Никакой гонки: короткие прогулки по долинам, катание на лошадях, купание в озере Искандеркуль, вечерние истории у костра и два дня в Душанбе с посещением зоопарка, фонтанов и парков. Дети — под присмотром опытных аниматоров, питание адаптировано под детское меню.',
      tj: 'Тур барои оилаҳо бо кӯдакон.',
      en: 'For families with kids from 5: horse rides, swims, campfires and two relaxed days in Dushanbe.',
    },
    images: [ORI.village, ORI.timurLake, ORI.active, IMG.hiker],
    destinationIds: ['dst-fann', 'dst-iskanderkul', 'dst-dushanbe'],
    categoryIds: ['cat-family', 'cat-trekking'],
    country: 'Таджикистан',
    city: 'Душанбе',
    region: 'Фанские горы / РРП',
    durationDays: 5,
    difficulty: 'easy',
    rating: 4.9,
    reviewsCount: 54,
    basePrice: 3200,
    discountPercent: 15,
    groupSizeMin: 4,
    groupSizeMax: 12,
    includes: [
      { ru: 'Трансферы', tj: 'Нақлиёт', en: 'Transfers' },
      { ru: 'Проживание (гостевые дома и кемпинг)', tj: 'Истиқомат', en: 'Accommodation' },
      { ru: 'Питание с детским меню', tj: 'Ғизо', en: 'Meals incl. kids menu' },
      { ru: 'Аниматор и детские развлечения', tj: 'Аниматор', en: 'Kids host' },
      { ru: 'Катание на лошадях', tj: 'Асп', en: 'Horse riding' },
    ],
    excludes: [
      { ru: 'Алкоголь', tj: 'Алкоголь', en: 'Alcohol' },
      { ru: 'Личные траты', tj: 'Хароҷот', en: 'Personal expenses' },
    ],
    whatToBring: [
      { ru: 'Детские лекарства', tj: 'Дору', en: 'Kids meds' },
      { ru: 'Купальники', tj: 'Майо', en: 'Swimsuits' },
    ],
    faq: [
      {
        q: { ru: 'С какого возраста можно?', tj: 'Аз чандсолагӣ?', en: 'Minimum age?' },
        a: { ru: 'От 5 лет. Для малышей до 5 лет — скидка 50%.', tj: 'Аз 5 сола.', en: 'From 5 years; under-5s get 50% off.' },
      },
    ],
    days: [
      { id: 'f1', day: 1, title: { ru: 'Душанбе, парки', tj: 'Паркҳо', en: 'Dushanbe parks' }, description: { ru: 'Прибытие, Набережная, парк отдыха, детский городок.', tj: 'Набережная.', en: 'Arrival, the riverfront and children\'s park.' } },
      { id: 'f2', day: 2, title: { ru: 'Дорога к Искандеркулю', tj: 'Искандаркӯл', en: 'To Iskanderkul' }, description: { ru: 'Пикник на перевале Анзоб, вечер у озера с фонариками.', tj: 'Пикник.', en: 'Picnic at Anzob pass, lake evening.' } },
      { id: 'f3', day: 3, title: { ru: 'Прогулка и лошади', tj: 'Асп', en: 'Walks & horses' }, description: { ru: 'Лёгкий трек к водопаду и катание на пони.', tj: 'Трек!', en: 'Gentle hike to the falls, pony rides.' } },
      { id: 'f4', day: 4, title: { ru: 'Ферма и сыр', tj: 'Сир', en: 'Farm & cheese' }, description: { ru: 'Горная ферма: коровы, барашки, сыр и лепёшки в тандыре.', tj: 'Ферма.', en: 'Mountain farm visit and tandyr flatbreads.' } },
      { id: 'f5', day: 5, title: { ru: 'Возвращение', tj: 'Бозгашт', en: 'Return' }, description: { ru: 'Чайхана, сувениры, вылет.', tj: 'Сувенирҳо.', en: 'Teahouse lunch, souvenirs, flight.' } },
    ],
    locations: [
      { id: 'ff1', stop: 1, name: { ru: 'Душанбе', tj: 'Душанбе', en: 'Dushanbe' }, lat: 38.5598, lng: 68.787 },
      { id: 'ff2', stop: 2, name: { ru: 'Искандеркуль', tj: 'Искандаркӯл', en: 'Iskanderkul' }, lat: 39.0778, lng: 68.3853 },
    ],
    extras: [
      { id: 'ex1', name: { ru: 'Фотосъёмка семьи', tj: 'Фото', en: 'Family photo session' }, price: 500 },
    ],
    startDates: ['2026-10-10', '2027-05-20', '2027-06-15', '2027-07-20'],
    featured: true,
    createdAt: '2026-04-10',
  },
  {
    id: 'tour-culture-food',
    slug: 'kultura-i-kuhnya-tadzhikistana',
    title: { ru: 'Культура и кухня Таджикистана', tj: 'Фарҳанг ва ошхонаи Тоҷикистон', en: 'Tajik Culture & Cuisine' },
    shortDescription: {
      ru: 'Пять дней вкуса и традиций: мастер-классы по плову, чайные церемонии и горные посёлки.',
      tj: 'Панҷ рӯзи таъми миллӣ.',
      en: 'Five days of taste and tradition: plov classes, tea rituals and mountain villages.',
    },
    description: {
      ru: 'Для тех, кто «влюбляется в страну через желудок». Научимся варить настоящий памирский плов и квадратные юфах, печь лепёшки в тандыре, узнаем правила национальной чайной церемонии и соберём травяной чай в горах. Побываем в гостях у гончаров Истаравшана и ткачей атласа, а вечером — ужин в семье в кишлаке.',
      tj: 'Барои дӯстдорони таоми миллӣ.',
      en: 'For lovers of real food culture: masterclasses, tea, crafts and village dinners.',
    },
    images: [ORI.ajina, ORI.kokGumbaz, ORI.silkCity, IMG.market],
    destinationIds: ['dst-dushanbe', 'dst-khujand'],
    categoryIds: ['cat-culture', 'cat-international'],
    country: 'Таджикистан',
    city: 'Душанбе / Истаравшан',
    region: 'РРП / Согдиана',
    durationDays: 5,
    difficulty: 'easy',
    rating: 4.8,
    reviewsCount: 41,
    basePrice: 2500,
    groupSizeMin: 2,
    groupSizeMax: 10,
    includes: [
      { ru: 'Все мастер-классы', tj: 'Дарсҳо', en: 'All masterclasses' },
      { ru: 'Проживание', tj: 'Истиқомат', en: 'Accommodation' },
      { ru: 'Все блюда по программе', tj: 'Ғизо', en: 'Programme meals' },
      { ru: 'Гид-повар', tj: 'Роҳбалад', en: 'Guide-chef' },
      { ru: 'Трансферы', tj: 'Нақлиёт', en: 'Transfers' },
    ],
    excludes: [
      { ru: 'Алкоголь (кроме местного вина)', tj: 'Алкоголь', en: 'Alcohol' },
      { ru: 'Сувениры', tj: 'Сувенирҳо', en: 'Souvenirs' },
    ],
    whatToBring: [
      { ru: 'Свободная одежда', tj: 'Либос', en: 'Loose clothing' },
      { ru: 'Записную книжку для рецептов', tj: 'Дафтар', en: 'Notebook for recipes' },
    ],
    faq: [
      {
        q: { ru: 'Подойдёт вегетарианцам?', tj: 'Барои вегетарианҳо?', en: 'Vegetarian-friendly?' },
        a: { ru: 'Да — адаптируем меню под любой стиль питания при бронировании.', tj: 'Ҳа.', en: 'Yes, we adapt the menu on request.' },
      },
    ],
    days: [
      { id: 'cu1', day: 1, title: { ru: 'Плов: наука и искусство', tj: 'Дарси палав', en: 'Plov masterclass' }, description: { ru: 'Базар Мехргон, секреты риса девзира, вечерний плов на дровах.', tj: 'Палав дар оташ.', en: 'Mehrgon bazaar and plov over wood fire.' } },
      { id: 'cu2', day: 2, title: { ru: 'Муксу и казаны', tj: 'Муксу', en: 'Mukhs & kazans' }, description: { ru: 'Драконовые супы, знакомство со специями Гиссарской долины.', tj: 'Специяҳо.', en: 'Herbal soups and Hissar spices.' } },
      { id: 'cu3', day: 3, title: { ru: 'Тандыр и лепёшки', tj: 'Тандир', en: 'Tandyr flatbreads' }, description: { ru: 'Утренняя печь, дегустация и урок символики узоров на лепёшках.', tj: 'Нон.', en: 'Bake flatbreads, learn their symbolic patterns.' } },
      { id: 'cu4', day: 4, title: { ru: 'Истаравшан: гончары', tj: 'Истаравшан', en: 'Istaravshan potters' }, description: { ru: 'Гончарные ряды, атлас и шёлковое адрас, ужин у семьи.', tj: 'Кулолон.', en: 'Potters, atlas silk and a village dinner.' } },
      { id: 'cu5', day: 5, title: { ru: 'Чайная церемония', tj: 'Чойхона', en: 'Tea ceremony' }, description: { ru: 'Национальная чайхана, проводы и рецепты с собой.', tj: 'Чойхона.', en: 'The national teahouse and farewell letters of recipes.' } },
    ],
    locations: [
      { id: 'cu1', stop: 1, name: { ru: 'Душанбе', tj: 'Душанбе', en: 'Dushanbe' }, lat: 38.5598, lng: 68.787 },
      { id: 'cu2', stop: 2, name: { ru: 'Истаравшан', tj: 'Истаравшан', en: 'Istaravshan' }, lat: 39.9108, lng: 69.0031 },
    ],
    extras: [
      { id: 'ex1', name: { ru: 'Дополнительный винный тур', tj: 'Вин', en: 'Wine tour' }, price: 450 },
    ],
    startDates: ['2026-10-14', '2027-04-28', '2027-05-26'],
    createdAt: '2026-03-25',
  },
]